### ISSUE TITLE
Where are warps stored on server?

### ISSUE THREAD

**Issue by delawarehunter** [CodedSakura/FabricWarps#6]
Where are the warps stored on the server?  We seem to lose them whenever we have to updated a modpack that we use.  Can't seem to find them.  Thanks in advance.

**Comment by CodedSakura** [comment]
(if i recall correctly) the warps are stored in the world's data folder, in `cardinal_world_components.dat`

**Comment by delawarehunter** [comment]
Interesting... I moved my entire world, mod, and config folders from one server to a new server but I lost all of my warps.  So, doesn't seem like that's the case unless I just flat out missed something... but every single other aspect of the world folder copied over without any issue.

**Comment by SaiCode-DEV** [comment]
I got the issue too... whenever i launch the server without FabricWarps / homes installed, all homes and warp points get lost. I would love the feature to store it to a separate file

**Comment by CodedSakura** [comment]
ah, that's an interesting point - i hadn't considered what happens if a world is launched without the mod..

**Comment by SaiCode-DEV** [comment]
have to do that ALL the time... annoying but at least you could copy it using NBT editors.

**Comment by CodedSakura** [comment]
i will definitely consider adding either import/export or saving to an external file in the upcoming™ rewrite of my mods!

**Comment by SaiCode-DEV** [comment]
> upcoming™
sounds like it should be soonisch™ xD 
Technically you already have the config file, so you could try redirecting everything in there.

**Comment by CodedSakura** [comment]
the current config is not in any way appropriate for warp storage, something like JSON or a database would be a lot better. Also i think it would be better if the warps were stored separately for each world, not for the whole client or server install

**Comment by SaiCode-DHBW** [comment]
Yeah... the same issue is with Fabric Homes, but creating issues twice is kinda dumb
